# Generated by Django 4.0.5 on 2022-06-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
